/* Test1 bulk orchestration; calculations remain in app.js. */
(() => {
  'use strict';
  if (new URLSearchParams(location.search).has('batch-worker')) {
    document.querySelector('header')?.remove();
    document.getElementById('lakeDataDetails')?.closest('section')?.remove();
    document.querySelector('footer')?.remove();
    document.querySelectorAll('main > section').forEach(section => { if (!['dataSection','resultsSection'].includes(section.id)) section.style.display='none'; });
    document.getElementById('dataSection').style.display='none';
    ['runValidationBtn','buildFinalBtn'].forEach(id=>document.getElementById(id).style.display='none');
    return;
  }
  const main=document.querySelector('main');
  const first=document.getElementById('downloadTemplateBtn').closest('section');
  const tabs=document.createElement('div'); tabs.className='panel action-row'; tabs.setAttribute('role','tablist'); tabs.setAttribute('aria-label','Model processing mode');
  const single=document.createElement('div');
  for(let next=first;next;) { const following=next.nextElementSibling; single.append(next); next=following; }
  main.append(tabs,single);
  const bulk=document.createElement('section'); bulk.className='panel'; bulk.hidden=true;
  bulk.innerHTML=`<h2>Bulk processing</h2><p>One CSV per lake. Each lake uses the same independent calibration, chronological validation and final model as Single Lake. Files stay in your browser.</p>
    <div class="action-row"><label>Temporal resolution <select id="bulkFrequency"><option>Daily</option><option>Monthly</option><option>Yearly</option></select></label>
    <label>Calibration share (%) <input id="bulkSplit" type="number" min="50" max="90" value="70" step="1"></label></div>
    <label class="field-label">Upload lake CSV files <input id="bulkFiles" type="file" accept=".csv,text/csv" multiple></label>
    <p id="bulkSelection" class="helper">Select multiple files together, or add files in successive selections.</p>
    <div class="action-row"><button id="bulkClear" type="button" class="button button--ghost">Clear files</button><button id="bulkRun" type="button" class="button button--primary" disabled>Run all lakes</button><button id="bulkCancel" type="button" class="button button--ghost" disabled>Stop after current lake</button></div>
    <p id="bulkStatus" role="status" class="status-box">No lake files selected.</p><progress id="bulkProgress" max="1" value="0" style="width:100%"></progress>
    <div class="action-row"><button id="bulkSummary" type="button" class="button button--secondary" disabled>Download summary CSV</button><button id="bulkZip" type="button" class="button button--secondary" disabled>Prepare all lakes detailed results (ZIP)</button><button id="bulkPng" type="button" class="button button--ghost" disabled>Download all PNG charts (ZIP)</button></div>
    <div class="table-wrap"><table><thead id="bulkHead"></thead><tbody id="bulkBody"></tbody></table></div>
    <label id="bulkViewLabel" hidden>View lake results <select id="bulkView"></select></label><h3 id="bulkLakeTitle"></h3>
    <iframe id="bulkFrame" title="Separate lake model results and charts" style="width:100%;height:2400px;border:0" hidden></iframe>`;
  main.append(bulk);
  const $=id=>document.getElementById(id);
  ['Single Lake','Bulk Processing'].forEach((name,i)=>{ const b=document.createElement('button');b.type='button';b.textContent=name;b.className='button button--secondary';b.setAttribute('role','tab');b.setAttribute('aria-selected',String(!i));b.addEventListener('click',()=>{single.hidden=!!i;bulk.hidden=!i;[...tabs.children].forEach((t,j)=>t.setAttribute('aria-selected',String(i===j)));});tabs.append(b);});
  const queue=[], results=[]; let running=false, stop=false, ready=null;
  const columns=['lake','frequency','status','rows','observations','tau','M','beta0','betaT','betaS','betaU','calibration_RMSE','calibration_MAE','calibration_R2','training_observations','held_out_observations','validation_RMSE','validation_MAE','validation_R2','validation_bias','validation_tau','validation_M','final_tau','final_beta0','final_betaT','final_betaS','final_betaU','message'];
  function summary(r) { const x=r.result,f=x?.fit,v=x?.validation,ff=x?.finalFit;return [r.name,x?.frequency||r.frequency,r.error?'Failed':x?.validationError?'Validation unavailable':'Complete',x?.rows.length,f?.nObserved,f?.tau,f?Math.exp(-1/f.tau):null,f?.beta0,f?.betaT,f?.betaS,f?.betaU,f?.rmse,f?.mae,f?.r2,v?.split.trainIdx.length,v?.split.testIdx.length,v?.stats.rmse,v?.stats.mae,v?.stats.r2,v?.stats.bias,v?.fit.tau,v?Math.exp(-1/v.fit.tau):null,ff?.tau,ff?.beta0,ff?.betaT,ff?.betaS,ff?.betaU,r.error||x?.validationError||'']; }
  function csvCell(v) { return '"'+String(v??'').replace(/"/g,'""')+'"'; }
  function summaryCSV(){return [columns,...results.map(summary)].map(row=>row.map(csvCell).join(',')).join('\n');}
  function save(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  function draw(){ $('bulkHead').replaceChildren();const tr=document.createElement('tr');columns.forEach(c=>{const th=document.createElement('th');th.textContent=c;tr.append(th);});$('bulkHead').append(tr);$('bulkBody').replaceChildren();results.forEach(r=>{const row=document.createElement('tr');summary(r).forEach(v=>{const td=document.createElement('td');td.textContent=typeof v==='number'?Number.isFinite(v)?v.toFixed(4):'—':v??'—';row.append(td);});$('bulkBody').append(row);});}
  function controls(){ ['bulkFiles','bulkClear','bulkFrequency','bulkSplit'].forEach(id=>$(id).disabled=running);$('bulkRun').disabled=running||!queue.length;$('bulkCancel').disabled=!running;['bulkSummary','bulkZip','bulkPng'].forEach(id=>$(id).disabled=running||!results.length);$('bulkView').disabled=running; }
  $('bulkFiles').addEventListener('change',e=>{for(const file of e.target.files) {if(!/\.csv$/i.test(file.name)){ $('bulkStatus').textContent='Choose CSV files only.';continue;}const key=file.name+'|'+file.size+'|'+file.lastModified;if(!queue.some(q=>q.key===key))queue.push({key,file});}$('bulkSelection').textContent=queue.length+' lake CSV files selected: '+queue.map(q=>q.file.name).join(', ');controls();e.target.value='';});
  $('bulkClear').addEventListener('click',()=>{queue.length=0;$('bulkSelection').textContent='No files selected.';controls();});
  function worker(){ if(!ready)ready=new Promise((resolve,reject)=>{const frame=$('bulkFrame');frame.addEventListener('load',()=>{const win=frame.contentWindow;if(win.__lakeBatch)resolve(win);else reject(Error('Could not load the separate lake model.'));},{once:true});frame.src='index.html?batch-worker=1';});return ready; }
  function view(index){const r=results[index];if(!r?.result)return;worker().then(win=>{win.__lakeBatch.show(r.result);$('bulkLakeTitle').textContent=r.name+' — '+r.result.frequency;$('bulkFrame').hidden=false;});}
  $('bulkView').addEventListener('change',()=>view(Number($('bulkView').value)));
  $('bulkCancel').addEventListener('click',()=>{stop=true;$('bulkStatus').textContent='Stopping after the current lake finishes.';});
  $('bulkRun').addEventListener('click',async()=>{const percent=Number($('bulkSplit').value);if(!Number.isInteger(percent)||percent<50||percent>90){$('bulkStatus').textContent='Choose calibration share from 50 to 90%.';return;}running=true;stop=false;readyDownload.hidden=true;results.length=0;$('bulkView').replaceChildren();$('bulkViewLabel').hidden=true;$('bulkFrame').hidden=true;controls();draw();const frequency=$('bulkFrequency').value;$('bulkProgress').max=queue.length;$('bulkProgress').value=0;
    try {const win=await worker();for(let i=0;i<queue.length;i++){if(stop)break;const file=queue[i].file;const r={name:file.name,frequency};try{r.result=await win.__lakeBatch.run(await file.text(),file.name,frequency,percent,stage=>$('bulkStatus').textContent=(i+1)+' / '+queue.length+' · '+file.name+' · '+stage);}catch(e){r.error=e.message;}results.push(r);if(r.result){const option=document.createElement('option');option.value=String(results.length-1);option.textContent=r.name;$('bulkView').append(option);}draw();$('bulkProgress').value=i+1;await new Promise(resolve=>setTimeout(resolve,0));}$('bulkStatus').textContent=(stop?'Stopped. ':'Completed. ')+results.filter(r=>r.result).length+' lakes modelled; '+results.filter(r=>r.error).length+' failed. Validation issues are listed separately.';$('bulkViewLabel').hidden=!$('bulkView').options.length;if($('bulkView').options.length)view(Number($('bulkView').value));}catch(e){$('bulkStatus').textContent=e.message;ready=null;}finally{running=false;controls();}});
  $('bulkSummary').addEventListener('click',()=>save(new Blob([summaryCSV()],{type:'text/csv;charset=utf-8'}),'lake-model-summary.csv'));
  // Store-only ZIP writer: no external library or network dependency.
  async function zip(entries){const encoder=new TextEncoder(),locals=[],central=[];let offset=0;const table=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});for(const [path,value] of Object.entries(entries)){const name=encoder.encode(path),data=value && typeof value.arrayBuffer === 'function'?new Uint8Array(await value.arrayBuffer()):encoder.encode(value);let crc=0xffffffff;for(const byte of data)crc=table[(crc^byte)&255]^(crc>>>8);crc=(crc^0xffffffff)>>>0;const local=new Uint8Array(30+name.length),lv=new DataView(local.buffer);lv.setUint32(0,0x04034b50,true);lv.setUint16(4,20,true);lv.setUint16(6,0x800,true);lv.setUint32(14,crc,true);lv.setUint32(18,data.length,true);lv.setUint32(22,data.length,true);lv.setUint16(26,name.length,true);local.set(name,30);const c=new Uint8Array(46+name.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,crc,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);c.set(name,46);locals.push(local,data);central.push(c);offset+=local.length+data.length;}const size=central.reduce((n,c)=>n+c.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,central.length,true);ev.setUint16(10,central.length,true);ev.setUint32(12,size,true);ev.setUint32(16,offset,true);if(central.length>65535||offset+size>0xffffffff)throw Error('Archive exceeds ZIP capacity. Download smaller batches.');return new Blob([...locals,...central,end],{type:'application/zip'});}
  let archiveUrl=null;
  const readyDownload=document.createElement('a');readyDownload.className='button button--primary';readyDownload.hidden=true;readyDownload.textContent='Download prepared ZIP';
  $('bulkZip').parentElement.after(readyDownload);
  async function archive(format){running=true;controls();readyDownload.hidden=true;try{const win=await worker(),entries={'summary.csv':summaryCSV(),'README.txt':'Each numbered folder contains one lake. input.csv preserves the model input rows; detailed_timeseries.csv includes separate calibration, final and validation free runs. reconstruction.csv uses the existing observation-anchored reconstruction. Residuals are predicted minus observed. Validation metrics use only held-out observations. Parameters are fitted separately for each lake. A failed lake has error.txt. Charts are SVG in the detailed ZIP. PNG charts are available separately.'};for(let i=0;i<results.length;i++){const r=results[i];const prefix=String(i+1).padStart(3,'0')+'_'+r.name.replace(/\.csv$/i,'').replace(/[^a-zA-Z0-9_-]/g,'_')+'/';$('bulkStatus').textContent='Preparing '+format.toUpperCase()+' archive '+(i+1)+' / '+results.length;if(r.error){entries[prefix+'error.txt']=r.error;continue;}const files=win.__lakeBatch.files(r.result);if(format==='svg')Object.entries(files).forEach(([n,data])=>{if(data)entries[prefix+n]=data;});try{Object.entries(await win.__lakePlotExports(format)).forEach(([n,data])=>entries[prefix+n]=data);}catch(chartError){entries[prefix+'chart_export_error.txt']=chartError.message;}}const blob=await zip(entries);if(archiveUrl)URL.revokeObjectURL(archiveUrl);archiveUrl=URL.createObjectURL(blob);readyDownload.href=archiveUrl;readyDownload.download=format==='svg'?'all-lakes-detailed-results.zip':'all-lakes-charts-png.zip';readyDownload.hidden=false;$('bulkStatus').textContent='ZIP ready for '+results.length+' lakes. Tap Download prepared ZIP to save it.';}catch(e){$('bulkStatus').textContent='Archive failed: '+e.message;}finally{running=false;controls();view(Number($('bulkView').value));}}
  $('bulkZip').addEventListener('click',()=>archive('svg'));$('bulkPng').addEventListener('click',()=>archive('png'));
})();
